## Handwerkliche Ãœbungsaufgaben zu den Datenbank-Operationen in Pandas

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

In [3]:
aisles = pd.read_csv('aisles.csv')
departments = pd.read_csv('departments.csv')
orders = pd.read_csv('orders.csv')
products = pd.read_csv('products.csv')

In [4]:
orders.head(n=20)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
5,3367565,1,prior,6,2,7,19.0
6,550135,1,prior,7,1,9,20.0
7,3108588,1,prior,8,1,14,14.0
8,2295261,1,prior,9,1,16,0.0
9,2550362,1,prior,10,4,8,30.0
10,1187899,1,train,11,4,8,14.0
11,2168274,2,prior,1,2,11,NaN
12,1501582,2,prior,2,5,10,10.0
13,1901567,2,prior,3,1,10,3.0
14,738281,2,prior,4,2,10,8.0
15,1673511,2,prior,5,3,11,8.0
16,1199898,2,prior,6,2,9,13.0
17,3194192,2,prior,7,2,12,14.0
18,788338,2,prior,8,1,15,27.0
19,1718559,2,prior,9,2,9,8.0

# Aufgabe 1:
Zum 'orders' DataFrame soll eine Spalte 'factor' hinzugefÃ¼gt werden, die fÃ¼r jede Bestellung jeweils einen Wert d/dm enthÃ¤lt, wobei d 'days_since_prior_order' der betreffenden Bestellung ist, und dm der Durchschnitt der 'days_since_prior_order' aller Bestellungen des jeweiligen Users. Mit anderen Worten: Der Wert der neuen 'orders'-Spalte soll anzeigen, welche Bestellungen eines Users gemessen am Ã¼blichen Verhalten dieses Users schnell nach der vorhergehenden Bestellung erfolgt sind. 
### Zeigen Sie als Ergebnis die gleichen 20 ersten Zeilen des 'oders'DataFrame wie oben, aber ergÃ¤nzu um die neue 'factors'-Spalte.

# Aufgabe 2:
Erzeuegen Sie und lassen Sie ausgeben eine Tabelle, die fÃ¼r jeden der 7 Wochentage anzeigt, welcher Anteil der Bestellungen 'organic bananas' enthÃ¤lt

# Aufgabe 3:
##### Berechnen Sie und lassen Sie ausgeben: Wie wahrscheinlich ist es, dass die nÃ¤chste Bestellung eines Users 'organic bananas' enthÃ¤lt ...
##### a) ... wenn die vorherige Bestellung organic bananas enthalten hat.
##### b) ... wenn die vorherige Bestellung KEINE organic bananas enthalten hat.
##### c) ... ohne Unterscheidung nach dem Inhalt der vorherigen Bestellung.

Verwenden Sie als SchÃ¤tzwert fÃ¼r die gesuchte Wahrscheinlichkeit die relative HÃ¤ufigkeit aus den vorliegenden Daten. Es soll keine User-spezifische SchÃ¤tzung erfolgen (dafÃ¼r wÃ¼rde die Datenmenge auch nicht ausreichen), sondern fÃ¼r jede der Teilaufgaben soll EIN Wert Ã¼ber alle User hinweg ermittelt werden.